Repository frenck/python-wled, pull requests merged in 2021-06, with the labels that each got.

#299 Reduce state lookups
  src/wled/models.py
Labels: refactor

#233 Add new leds property 'wv'
  pyproject.toml
  src/wled/models.py
  tests/test_wled.py
Labels: new-feature

#302 Add fps property to device info data
  src/wled/models.py
Labels: new-feature

#303 Add websocket property to Info object
  src/wled/models.py
Labels: new-feature

#304 Add WebSocket support
  examples/websocket.py
  src/wled/__init__.py
  src/wled/exceptions.py
  src/wled/wled.py
Labels: new-feature

#305 Drop Python 3.7 support
  README.md
  mypi.ini
Labels: breaking-change

#298 Add handling of live override mode
  src/wled/__init__.py
  src/wled/models.py
  src/wled/wled.py
  tests/test_wled.py
Labels: new-feature

#314 Remove deprecated pin info
  src/wled/models.py
Labels: breaking-change

#315 Add Nightlight mode, extract deprecated nightlight fade from mode
  src/wled/models.py
Labels: new-feature

#321 Add ability to reboot device
  examples/control.py
  src/wled/wled.py
  tests/test_wled.py
Labels: new-feature

#322 Add support for WLED presets
  examples/control.py
  src/wled/__init__.py
  src/wled/models.py
  src/wled/wled.py
Labels: new-feature
