Repository frenck/python-wled, pull requests merged in 2024-07, with the labels that each got.

#1396 Unfreeze models for easier testing
  src/wled/models.py
Labels: enhancement, bugfix

#1378 Case-insensitive comparison of architecture values
  src/wled/models.py
Labels: bugfix

#1367 Add CCT support
  src/wled/models.py
  src/wled/wled.py
Labels: new-feature
