Repository frenck/python-wled, pull requests merged in 2024-05, with the labels that each got.

#1266 Refactor models to improve performance
  src/wled/models.py
Labels: enhancement

#1213 Fix firmware upgrade for 2M ESP8266 boards
  src/wled/wled.py
Labels: enhancement, stale

#1331 Initial CLI setup
  .devcontainer/devcontainer.json
  .github/workflows/linting.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .github/workflows/typing.yaml
  README.md
  poetry.lock
  pyproject.toml
  src/wled/cli/__init__.py
  src/wled/cli/async_typer.py
Labels: new-feature
